# This file was generated by GoReleaser. DO NOT EDIT.
cask "portlight" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ec8b9a829e51809d702936e6eedcd1bf3717062e923b0f00d631a4f697f5ad3a"
      url "https://github.com/tudiapps/portlight-cli/releases/download/v#{version}/portlight_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "40260ac1c6900be854bff367ea4fc54841842d21465aa7879b43baddb1b50578"
      url "https://github.com/tudiapps/portlight-cli/releases/download/v#{version}/portlight_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "853044aeab64ad5aaaf4ba1c9dcd890f1a5be30a6a875ca46332748450fed2be"
      url "https://github.com/tudiapps/portlight-cli/releases/download/v#{version}/portlight_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b985613b790440a3ea1d30c814baca1e8d9e28e0f07194b33d5ac9c65c96a67"
      url "https://github.com/tudiapps/portlight-cli/releases/download/v#{version}/portlight_#{version}_linux_amd64.tar.gz"
    end
  end

  name "portlight"
  desc "Desktop companion for the Portlight app — pair SSH hosts and keys with your phone"
  homepage "https://github.com/tudiapps/portlight-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portlight"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portlight"]
    end
  end

  # No zap stanza required
end
